//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictorBusesArrival
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationForecast
    {
        public int Id { get; set; }
        public Nullable<int> Arrt { get; set; }
        public string Where { get; set; }
        public string Vehid { get; set; }
        public Nullable<int> Rid { get; set; }
        public string Rtype { get; set; }
        public Nullable<int> Rnum { get; set; }
        public string Lastst { get; set; }
    }
}
