//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictorBusesArrival
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationForecast
    {
        public int Id { get; set; }
        public Nullable<int> ArTime { get; set; }
        public Nullable<int> Where { get; set; }
        public Nullable<int> VehicalId { get; set; }
        public Nullable<int> RoutId { get; set; }
        public string RoutType { get; set; }
        public Nullable<int> RoutNumber { get; set; }
        public string LastStation { get; set; }
    }
}
